fix: git act

diff --git a/.github/workflows/deploy_to_gh_pages.yml b/.github/workflows/deploy_to_gh_pages.yml
--- a/.github/workflows/deploy_to_gh_pages.yml
+++ b/.github/workflows/deploy_to_gh_pages.yml
@@ -7,6 +7,9 @@ on:
   push:
     branches: [main]
 
+  # Allows you to run this workflow manually from the Actions tab
+  workflow_dispatch:
+
 jobs:
   build:
     runs-on: ubuntu-latest
@@ -21,30 +24,59 @@ jobs:
       NEXT_PUBLIC_APP_SITE_URL: ${{secrets.NEXT_PUBLIC_APP_SITE_URL}}
       NEXT_PUBLIC_APP_VERSION: ${{secrets.NEXT_PUBLIC_APP_VERSION}}
 
-    strategy:
-      matrix:
-        node-version: [16.x]
-        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
-
     steps:
-      - uses: actions/checkout@v2
+      - name: Checkout
+        uses: actions/checkout@v4
 
-      - name: Use Node.js ${{ matrix.node-version }}
-        uses: actions/setup-node@v2
+      - name: Detect package manager
+        id: detect-package-manager
+        run: |
+          if [ -f "${{ github.workspace }}/yarn.lock" ]; then
+            echo "manager=yarn" >> $GITHUB_OUTPUT
+            echo "command=install" >> $GITHUB_OUTPUT
+            echo "runner=yarn" >> $GITHUB_OUTPUT
+            exit 0
+          elif [ -f "${{ github.workspace }}/package.json" ]; then
+            echo "manager=npm" >> $GITHUB_OUTPUT
+            echo "command=ci" >> $GITHUB_OUTPUT
+            echo "runner=npx --no-install" >> $GITHUB_OUTPUT
+            exit 0
+          else
+            echo "Unable to determine package manager"
+            exit 1
+          fi
+
+      - name: Setup nodes
+        uses: actions/setup-node@v4
         with:
-          node-version: ${{ matrix.node-version }}
-          # cache: 'yarn'
+          node-version: 'lts/*'
+          cache: ${{ steps.detect-package-manager.outputs.manager }}
 
-      - name: Install packages
-        run: npm run install
+      - name: Setup Pages
+        uses: actions/configure-pages@v4
 
-      - name: Build the project
-        run: npm build
+      - name: Restore cache
+        uses: actions/cache@v4
+        with:
+          path: |
+            .next/cache
+          # Generate a new cache whenever packages or source files change.
+          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json', '**/yarn.lock') }}-${{ hashFiles('**.[jt]s', '**.[jt]sx') }}
+          # If source files changed but packages didn't, rebuild from a prior cache.
+          restore-keys: |
+            ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json', '**/yarn.lock') }}-
+
+      - name: Install dependencies
+        run: ${{ steps.detect-package-manager.outputs.manager }} ${{ steps.detect-package-manager.outputs.command }}
+
+      - name: Build with Next.js
+        run: ${{ steps.detect-package-manager.outputs.runner }} next build
 
       - name: Run unit tests
-        run: npm test
+        run: ${{ steps.detect-package-manager.outputs.runner }} test
 
       - name: Build the website
+        # Place a .nojekyll file in the /public directory to disable GitHub Pages from trying to create a Jekyll website.
         run: npm run export && touch ./out/.nojekyll
         # This below is used to build storybook static site with whole site together
         # run: npm run export-with-storybook && touch ./out/.nojekyll
